### ISSUE TITLE
errors compiling and with tests

### ISSUE THREAD

**Issue by nicx256** [6cdh/tree-sitter-scheme#11]
trying to use tree-sitter-scheme from my program like so:

> p.set_language(&tree_sitter_scheme::LANGUAGE.into()).expect("error loading scheme grammar");

i get the compiler error 

>the trait `From<LanguageFn>` is not implemented for `tree_sitter::Language`, which is required by `LanguageFn: Into<_>`

also, trying to run `cargo test` in the tree-sitter-scheme repo outputs an error:

> error[E0433]: failed to resolve: use of undeclared crate or module `tree_sitter`
>  --> bindings/rust/lib.rs:48:26
>    |
> 48 |         let mut parser = tree_sitter::Parser::new();
>    |                          ^^^^^^^^^^^ use of undeclared crate or module `tree_sitter`

**Comment by 6cdh** [comment]
Thanks for your report.

These language bindings are generated by upstream tree-sitter cli.

There is a bug in 0.23 cli that it generated incorrect 0.22 tree-sitter dev dependencies instead of 0.23.

**Comment by nicx256** [comment]
Ah, the test works now, thanks for the quick reply! Think the other problem was my code using a wrong version somehow.
