### ISSUE TITLE
Nested comment blocks

### ISSUE THREAD

**Issue by archseer** [6cdh/tree-sitter-scheme#2]
The comment block seems to end at the first `|#` pair, rather than the last matching one.

```scheme
#| Block comments
   can span multiple lines and...
   #| can be nested
   |#
|#
```

**Comment by 6cdh** [comment]
Yes, it's a bug. I thought it works like C style block comment `/**/`. But it's not.

**Comment by 6cdh** [comment]
0d7403bb639925a2d14a858b16461e74b950b384 should fix it.
I'll open a pull request to update nvim-treesitter queries once its `lockfile.json` updates.

**Comment by archseer** [comment]
Thanks! Great grammar by the way, I'm currently integrating it into [helix](https://github.com/helix-editor/helix).

**Comment by 6cdh** [comment]
Yeah, I've heard it. It's an interesting project. I will try it if I have time.

The new scheme highlight is merged into nvim-tree-sitter now. I also fixed the "λ" highlight. You can copy or reference it.

You can also use this grammar for query files. It is also designed to support these DSLs of Scheme naturally.

There are many features unsupported. For example, here-doc in chicken scheme, special identifier like `1+` in chez scheme. Different scheme implementations may have even conflict syntax. That means some syntax can't get parsed correctly.

So be careful before make it default in helix.
